default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: VideoAnalyticsApi_development

test:
  <<: *default
  database: VideoAnalyticsApi_test

production:
  <<: *default
  database: VideoAnalyticsApi_production
  username: video-analytics-api
  password: <%= ENV['VIDEO-ANALYTICS-API_DATABASE_PASSWORD'] %>
